name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Deploying to scrub-network-project

    steps:
      - name: Access Secrets
        run: |
          echo "Secret Token : ${{ secrets.VERCEL_ACCESS_TOKEN}}"
